/**
 * AnalyzedGame.js — Mongoose model for a single analyzed chess game
 *
 * Lifecycle: pending → analyzing → done | error
 *
 * Key sub-documents:
 *
 *   moveHistory  — one entry per move (both sides); populated by stockfishService.
 *     Fields: moveNum, color, san, evalAfterWhite (cp), winPct, delta (win% drop),
 *     classification (best/excellent/good/inaccuracy/mistake/blunder), bestMove (SAN).
 *
 *   mistakes     — subset of moveHistory where classification is blunder/mistake/inaccuracy.
 *     Extra fields: playedFen, evalBefore/After/Best (cp), winBefore/AfterPlayed/DropPct,
 *     category (tactical/hanging-piece/opening/endgame/positional/time-pressure/king-safety),
 *     explanation (Groq AI text), clockBefore (seconds remaining).
 *
 * Index: { userId, platform, gameId } — unique constraint prevents duplicate imports.
 *
 * @module models/AnalyzedGame
 */

const mongoose = require('mongoose');

// Per-move eval entry for ALL moves (both sides, populated after analysis)
const moveHistoryItemSchema = new mongoose.Schema({
  moveNum:        { type: Number, required: true },
  color:          { type: String, enum: ['white', 'black'], required: true },
  san:            { type: String, required: true },
  evalAfterWhite: { type: Number, required: true }, // centipawns from white's perspective
  winPct:         { type: Number, default: null },  // mover's win% after this move (0–100)
  delta:          { type: Number, default: 0 },     // win% drop (0 = best/no loss)
  classification: {
    type: String,
    enum: ['best', 'excellent', 'good', 'inaccuracy', 'mistake', 'blunder'],
    default: 'best',
  },
  bestMove: { type: String, default: null }, // engine's best SAN (only set when played ≠ best)
}, { _id: false });

// One entry per mistake/inaccuracy found in a game
const mistakeSchema = new mongoose.Schema({
  moveNumber:  { type: Number, required: true },
  color:       { type: String, enum: ['white', 'black'], required: true },
  played:      { type: String, required: true },   // e.g. "Rxe5"
  best:        { type: String, required: true },   // e.g. "Nf6"
  playedFen:   { type: String, required: true },   // position before the move
  evalBefore:     { type: Number, required: true },   // centipawns before move (mover's perspective)
  evalAfter:      { type: Number, required: true },   // centipawns after played move (mover's perspective)
  evalBest:       { type: Number, required: true },   // centipawns after best move (mover's perspective)
  winBefore:      { type: Number, default: null },    // mover's win% before move (0–100)
  winAfterPlayed: { type: Number, default: null },    // mover's win% after played move (0–100)
  winDropPct:     { type: Number, default: null },    // win% points lost (positive)
  delta:          { type: Number, required: true },   // cp difference (evalBest - evalAfter)
  type: {
    type: String,
    enum: ['blunder', 'mistake', 'inaccuracy'],
    required: true,
  },
  // Weakness category — set by classifier
  category: {
    type: String,
    enum: [
      'tactical',       // missed tactic (fork, pin, skewer etc.)
      'hanging-piece',  // left a piece undefended
      'opening',        // deviated badly in first 10 moves
      'endgame',        // mistake in simplified position (<7 pieces)
      'positional',     // strategic/positional error
      'time-pressure',  // clock was low when this happened
      'king-safety',    // weakened own king
      'other',
    ],
    default: 'other',
  },
  // AI explanation generated by Claude
  explanation: { type: String, default: null },
  clockBefore: { type: Number, default: null }, // seconds remaining
}, { _id: false });

const analyzedGameSchema = new mongoose.Schema({
  userId:     { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  platform:   { type: String, enum: ['chess.com', 'lichess'], required: true },
  gameId:     { type: String, required: true },  // platform's game ID
  pgn:        { type: String, required: true },
  playerColor: { type: String, enum: ['white', 'black'], required: true },
  opponent:   { type: String, required: true },
  playerRating:   { type: Number, default: null },
  opponentRating: { type: Number, default: null },
  result:     { type: String, enum: ['win', 'loss', 'draw'], required: true },
  timeControl: { type: String, default: null },
  playedAt:   { type: Date, default: null },
  opening:    { type: String, default: null }, // full name e.g. "Sicilian Defense: Najdorf Variation"
  eco:        { type: String, default: null }, // ECO code e.g. "B90"

  // Per-move evaluation history (all player moves)
  moveHistory: [moveHistoryItemSchema],

  // Analysis results
  mistakes:   [mistakeSchema],
  accuracy:   { type: Number, default: null },  // 0-100
  analysisStatus: {
    type: String,
    enum: ['pending', 'analyzing', 'done', 'error'],
    default: 'pending',
  },
}, { timestamps: true });

// Compound index — one analysis per user per game
analyzedGameSchema.index({ userId: 1, platform: 1, gameId: 1 }, { unique: true });

module.exports = mongoose.model('AnalyzedGame', analyzedGameSchema);
